config/routes.rb
Rails.application.routes.draw do
  
  get '/posts/report/' => 'posts#report'
  resources :likes
  resources :comments
  resources :posts

  
  get '/posts/publish/:id/:state' => 'posts#publish'
  get '/posts/view/:id' => 'posts#view'
  get '/posts/like/:id' => 'posts#like'

  
  root :to => 'posts#list'
  get '/posts/history/:post_id' => 'posts#history'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	#valitades :body, :presence => true
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
 	has_many :likes 	
  belongs_to :users
 	validates :body, :presence => true
  validates :body, :uniqueness => true

  

  
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  #protect_from_forgery with: :exception
  skip_before_filter :request_permissions
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  protect_from_forgery 

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    #@comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create    

    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to "/posts/view/"+@comment.post.id.to_s, notice: "Comentario creada exitosamente"
    else
      redirect_to "/posts/view/"+@comment.post.id.to_s, notice: "Error al crear Comentario"
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :body)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:show, :edit, :update, :destroy]

  # GET /likes
  # GET /likes.json
  def index
    @likes = Like.all
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes
  # POST /likes.json
  def create
    @like = Like.new(like_params)

     if @like.save
      redirect_to "/posts/view/"+@like.post.id.to_s, notice: "Usted le dio like a este post"
     else
      redirect_to "/posts/view/"+post.id.to_s, notice: "Error al dar like"
     end
  end

  # PATCH/PUT /likes/1
  # PATCH/PUT /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to @like, notice: 'Like was successfully updated.' }
        format.json { render :show, status: :ok, location: @like }
      else
        format.html { render :edit }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html { redirect_to likes_url, notice: 'Like was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def like_params
      params.require(:like).permit(:post_id)
    end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    #@posts = Post.all
    if params[:c] 
      @posts = Post.joins(:comments).where("comments.body LIKE '%#{params[:c]}%'").select("distinct posts.* ")
    elsif params[:category] and params[:category] != ""
      @posts = Post.where(:category=>params[:category])
    else
      q = params[:q] ? "body LIKE '%#{params[:q]}%'" : ""
      @posts = Post.where(q).order(:created_at).reverse  
    end
  end

  def list
    @posts = Post.where(:state=>'1').order(:created_at).reverse
    @count_words = Hash.new(0)
    @posts.map {|p| p.body}.join(" ").split(" ").each{ |word| @count_words[word]+=1}    
  end
  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  def view
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.state = '1'
    @post.user_id = 1
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post fue creado excitosamente.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def publish
    @post = Post.find(params[:id])
    @post.state = params[:state]
    @post.save!
    redirect_to posts_path, notice: 'Post fue actualizado en el Blog.'
  end

   def report

    @order = params[:order] ? params[:order] : 'id'
    @posts = Post.all
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post fue actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post fue eliminado corectamente.' }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :category, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BlogBasico" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <link rel="stylesheet" type="text/css" href="assets/jqcloud.css" />

    <%= javascript_include_tag "application" %>
    <script type="text/javascript" src="assets/jqcloud-1.0.3.min.js"></script>


  </head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand">Martin Arispe Riveros</a>
      </div>    
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">        
          <li><a href="/posts">Administrador</a> </li>
          <li><a href="/posts/report">Reporte</a></li>
        </ul>
      </div><!--/.nav-collapse -->          
    </div>
  </div>
    

    <div class="container">      
    <br><br><br><br><br>
            <%= yield %>
    </div> <!-- /container -->
        

     <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    <footer class="panel-footer">

        <div class="container">          
            <font color="black">Elaborado por: Martin Sebastian Arispe Riveros </font>          
        </div>
        <div class="copyright" align="right">
          <font color="black">Taller de Programacion - Universidad Catolica Boliviana "San Pablo".
        </div>
      </footer>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

  </body>
   

</html>

app/views/likes/_form.html.erb
<%= form_for(@like) do |f| %>
  <% if @like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
      <% @like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/likes/edit.html.erb
<h1>Editing like</h1>

<%= render 'form' %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

app/views/likes/index.html.erb
<h1>Listing likes</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @likes.each do |like| %>
      <tr>
        <td><%= like.post_id %></td>
        <td><%= link_to 'Show', like %></td>
        <td><%= link_to 'Edit', edit_like_path(like) %></td>
        <td><%= link_to 'Destroy', like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Like', new_like_path %>

app/views/likes/new.html.erb
<h1>New like</h1>

<%= render 'form' %>

<%= link_to 'Back', likes_path %>

app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @like.post_id %>
</p>

<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="panel panel-info">
  <div class="panel-heading"><center><h3><b></b></h3></center></div>
    <div align="center" class="panel-body">

  <div class="field">
    <p><b>Titulo</b></p><br>
    <%= f.text_field :title, { :class=>"form-control" } %>
  </div>
  <div class="field">
    <p><b>Contenido</b></p><br>
    <%= f.text_area :body, { :class=>"form-control" }%>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.select :category, ['Deportes','Politica','Otros'] %>
  </div>
  <div class="actions">
    <%= f.submit  %>    
    <%= link_to 'Volver', posts_path , { :class=>"btn btn-default" }%>
  </div>
  
  </div>
  </div>

</div>


<% end %>

app/views/posts/edit.html.erb
<h2>Editar Post</h2>

<%= render 'form' %>

<!--<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>-->

app/views/posts/index.html.erb
<h1>Lista de Posts</h1>

<div align="center">

<%= form_tag("/posts", :method => "get") do %>
  <%= label_tag(:q, "Buscar en post:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Buscar", { :class=>"btn btn-primary" }) %>
<% end %>

<%= form_tag("/posts", :method => "get") do %>
  <%= label_tag(:category, "Categoria:") %>
  <%= select_tag :category, options_for_select({'Todas'=>'','Deportes'=>'Deportes','Politica'=>'Politica','Otros'=>'Otros'}) %>
  <%= submit_tag("Buscar", { :class=>"btn btn-primary" } )  %>
<% end %>

<br>
</div>
<br><br><br>
<table <table class="table table-striped ">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Contenido</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Ver', post, { :class=>"btn btn-info" } %></td>
        <td><%= link_to 'Editar', edit_post_path(post), { :class=>"btn btn-warning" } %></td>
        <td><%= link_to 'Eliminar', post, method: :delete, data: { confirm: 'Estas seguro?'},  :class=>"btn btn-danger" %></td>
        <td><%= link_to post.state =='1' ? 'Despublicar': 'Publicado', '/posts/publish/'+ post.id.to_s + '/' + (post.state == '1' ? '0': '1'), { :class=>"btn btn-primary" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div align="right">
  <%= link_to 'Nuevo Post', new_post_path, { :class=>"btn btn-success" } %>
</div>

app/views/posts/list.html.erb
<% @posts.each do |post| %>
  <div class="panel panel-info">
    <h3 class="panel-heading">
      <%= link_to post.title, '/posts/view/'+post.id.to_s %><br>
	</h3> 		 
	<div align="right">
		<h5><b>Categoria:</b> <%=post.category%></h5>  
		<b>Usuario: </b><%= post.user_id %>
	</div>
	<p><h3><%= post.body %></h3></p>	    
	
	<div align="right">
		<%= (post.likes ? post.likes.count.to_s : '0')   + ' likes' %>
		 <form action="/likes" method="post">
      <input type="hidden" name="like[post_id]" value="<%=post.id%>">
      <input class="btn btn-primary btn-xs" type="submit" value="Like"> 
    </form>
		<h6 class="media-heading muted"><%= post.created_at.strftime("%d/%m/%Y %H:%M:%S") %><br></h6>
	</div>
  </div><br>
<% end %>

 

app/views/posts/new.html.erb
<h2>Nuevo Post</h2>

<%= render 'form' %>

app/views/posts/report.html.erb
<h2>Reporte </h2>
<br>

<table class="table table-striped ">
  <tr>
    <th> ID</th>
    <th> Titulo</th>
    <th> Fecha de Creacion</th>
    <th> Fecha de Modificacion</th>
    <th> Cantidad de Comentarios</th>
    <th> Cantidad de Likes</th>
    <th> Cantidad Palabras</th>
  </tr>



<% @posts.each do |post| %>
  <tr>
    <td><%= post.id %></td>
    <td><%= post.title %></td>
    <td><%= post.created_at %></td>
    <td><%= post.updated_at %></td>
    <td><%= post.comments.count %></td>
    <td><%= (post.likes ? post.likes.count.to_s : '0')  %></td>
    <td><%= post.body.split(' ').count %></td>
  </tr>
<% end %>
</table>

<br />

  

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<div class="panel panel-info">
  <div class="panel-heading"><center><h3><b><%= @post.title %></b></h3></center></div>

<br><br>
<p>
  
  <%= @post.body %><br>
  
</p>
	<div align="right">
	<div align="left"><b>Categoria:</b><%= @post.category %></div>
		<%= link_to 'Editar', edit_post_path(@post) , { :class=>"btn btn-warning" }%> 
		<%= link_to 'Volver', posts_path , { :class=>"btn btn-default" }%>
	</div>
</div>
</div>

app/views/posts/view.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-info">
  <div class="panel-heading"><center><h3><b><%= link_to @post.title, '/posts/view/'+@post.id.to_s %></b></h3></center></div>	
		<p ><h3>
			<%= @post.body %></h3>
		</p>
		<div align="right">
		<%= (@post.likes ? @post.likes.count.to_s : '0')   + ' likes' %>
		<form action="/likes" method="post">
			<input type="hidden" name="like[post_id]" value="<%=@post.id%>">
			<input class="btn btn-primary btn-xs"  type="submit" value="Like"> 
		</form>

		<h6 class="media-heading muted"><%= @post.created_at.strftime("%d/%m/%Y %H:%M:%S") %><br></h6>
		<br>
		</div>
		<div align="right">
			<%= link_to 'Volver', '/', {:class =>"btn btn-default"}%>
		</div>
</div>
<div class="panel panel-info">



<form action="/comments" method="post">
	<b>De un comentario:</b><br>
	<input type="hidden" name="comment[post_id]" value="<%=@post.id%>">
	&nbsp;&nbsp;&nbsp;&nbsp;<textarea name="comment[body]">
	</textarea>
	<br>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input  class="btn btn-primary" type="submit" value="Comentar"> 
</form>
<hr>

<% @post.comments.order(:created_at).reverse.each do |comment| %>
	<div class="media">
		<p>&nbsp;<%= comment.body %></p>		
		<p>&nbsp;<%= comment.created_at %></p>		
	</div>
<hr>
<% end %>		
</div>
</div>